Repository WoWs-Builder-Team/WoWs-ShipBuilder, pull requests merged in 2023-04, with the labels that each got.

#201 Add viewmodels caching to shipstats
  WoWsShipBuilder.Core/DataContainers/Armament/PingerGunDataContainer.cs
  WoWsShipBuilder.Core/DataContainers/Armament/TorpedoArmamentDataContainer.cs
  WoWsShipBuilder.Core/DataContainers/ModifierProcessor.cs
  WoWsShipBuilder.Core/DataContainers/Projectiles/ShellDataContainer.cs
  WoWsShipBuilder.Core/DataContainers/Projectiles/TorpedoDataContainer.cs
  WoWsShipBuilder.Core/DataContainers/Ship/ConsumableDataContainer.cs
  WoWsShipBuilder.Core/DataContainers/Ship/ManeuverabilityDataContainer.cs
  WoWsShipBuilder.Core/DataContainers/Ship/SurvivabilityDataContainer.cs
  WoWsShipBuilder.Core/Localization/Translation.Designer.cs
  WoWsShipBuilder.Core/Localization/Translation.resx
  WoWsShipBuilder.Core/WoWsShipBuilder.Core.csproj
  WoWsShipBuilder.Web/Components/CaptainSkillSelector.razor
  WoWsShipBuilder.Web/Components/ConsumableSelector.razor
  WoWsShipBuilder.Web/Components/DispersionPlot.razor
  WoWsShipBuilder.Web/Components/SharedFragments.razor
  WoWsShipBuilder.Web/Components/ShipModulesSelector.razor
  WoWsShipBuilder.Web/Components/ShipSelector.razor
  WoWsShipBuilder.Web/Components/ShipStatsComponent.razor
  WoWsShipBuilder.Web/Components/ShipStatsContainer.razor
  WoWsShipBuilder.Web/Components/ShipUpgradeSelector.razor
  WoWsShipBuilder.Web/Components/TopMenu.razor
  WoWsShipBuilder.Web/Dialogs/BuildConfigurationDialog.razor
  WoWsShipBuilder.Web/Dialogs/BuildConfigurationDialogHelper.razor
  WoWsShipBuilder.Web/Dialogs/BuildStringInputDialog.razor
  WoWsShipBuilder.Web/Dialogs/CustomAccelerationDataDialog.razor
  WoWsShipBuilder.Web/Dialogs/FiringAngleDialog.razor
  WoWsShipBuilder.Web/Dialogs/ShipBuildContainerSelectionDialog.razor
  WoWsShipBuilder.Web/Pages/AccelerationCharts.razor
  WoWsShipBuilder.Web/Pages/Charts.razor
  WoWsShipBuilder.Web/Pages/ShipComparison.razor
  WoWsShipBuilder.Web/Pages/ShipStats.razor
  WoWsShipBuilder.Web/Pages/UserSettings.razor
  WoWsShipBuilder.Web/Services/VmCache.cs
  WoWsShipBuilder.Web/Utility/Helpers.cs
  WoWsShipBuilder.Web/Utility/Validation.cs
  WoWsShipBuilder.Web/WoWsShipBuilder.Web.csproj
  WoWsShipBuilder.Web/wwwroot/scripts/MouseEventHelper.js
Labels: enhancement, Critical, Web

#204 Build data transfer between pages with shipBuildContainers
  WoWsShipBuilder.Core/Localization/Translation.Designer.cs
  WoWsShipBuilder.Core/Localization/Translation.resx
  WoWsShipBuilder.Web/Components/ShipSelector.razor
  WoWsShipBuilder.Web/Components/ShipStatsComponent.razor
  WoWsShipBuilder.Web/Components/ShipStatsContainer.razor
  WoWsShipBuilder.Web/Data/BuildTransferContainer.cs
  WoWsShipBuilder.Web/Dialogs/BuildStringInputDialog.razor
  WoWsShipBuilder.Web/Dialogs/ShipAndShellSelectionDialog.razor
  WoWsShipBuilder.Web/Dialogs/ShipBuildContainerSelectionDialog.razor
  WoWsShipBuilder.Web/Dialogs/ShipSelectionDialog.razor
  WoWsShipBuilder.Web/Pages/AccelerationCharts.razor
  WoWsShipBuilder.Web/Pages/Charts.razor
  WoWsShipBuilder.Web/Pages/Index.razor
  WoWsShipBuilder.Web/Pages/ShipComparison.razor
  WoWsShipBuilder.Web/Pages/ShipStats.razor
  WoWsShipBuilder.Web/Services/SessionStateCache.cs
  WoWsShipBuilder.Web/Utility/Helpers.cs
Labels: enhancement

#208 Migrate logging from NLog to Microsoft.Extensions.Logging
  WoWsShipBuilder.Core.Test/BuildTests/BuildDeserialization.cs
  WoWsShipBuilder.Core.Test/HttpTest/AwsClientTest.cs
  WoWsShipBuilder.Core.Test/LocalDataUpdaterTests/CheckJsonFileVersions.cs
  WoWsShipBuilder.Core.Test/LocalDataUpdaterTests/ShouldUpdaterRun.cs
  WoWsShipBuilder.Core.Test/LocalDataUpdaterTests/ValidateData.cs
  WoWsShipBuilder.Core/Builds/Build.cs
  WoWsShipBuilder.Core/DataContainers/Armament/PingerGunDataContainer.cs
  WoWsShipBuilder.Core/DataContainers/Armament/SecondaryBatteryDataContainer.cs
  WoWsShipBuilder.Core/DataContainers/Ship/ConsumableDataContainer.cs
  WoWsShipBuilder.Core/DataProvider/AppData.cs
  WoWsShipBuilder.Core/DataProvider/DesktopAppDataService.cs
  WoWsShipBuilder.Core/DataProvider/Updater/LocalDataUpdater.cs
  WoWsShipBuilder.Core/HttpClients/AwsClient.cs
  WoWsShipBuilder.Core/HttpClients/RetryHttpHandler.cs
  WoWsShipBuilder.Core/Logging.cs
  WoWsShipBuilder.Core/Utility/GameDataHelper.cs
  WoWsShipBuilder.Core/WoWsShipBuilder.Core.csproj
  WoWsShipBuilder.UI/App.axaml.cs
  WoWsShipBuilder.UI/Converters/ConsumableUiConverter.cs
  WoWsShipBuilder.UI/Converters/ImagePathConverter.cs
  WoWsShipBuilder.UI/DesignDataHelper.cs
  WoWsShipBuilder.UI/Program.cs
  WoWsShipBuilder.UI/Settings/AppSettingsHelper.cs
  WoWsShipBuilder.UI/Translations/LocalizeConverter.cs
  WoWsShipBuilder.UI/UserControls/ShipStatsControl.axaml.cs
  WoWsShipBuilder.UI/Utilities/ClipboardHelper.cs
  WoWsShipBuilder.UI/Utilities/LoggingSetup.cs
  WoWsShipBuilder.UI/Utilities/WindowScalingHelper.cs
  WoWsShipBuilder.UI/ViewModels/Dialog/BuildImportViewModel.cs
  WoWsShipBuilder.UI/ViewModels/DispersionPlot/DispersionGraphViewModel.cs
  WoWsShipBuilder.UI/ViewModels/ScreenshotContainerViewModel.cs
  WoWsShipBuilder.UI/ViewModels/ShipVm/ShipWindowViewModel.cs
  WoWsShipBuilder.UI/ViewModels/StartMenuViewModel.cs
  WoWsShipBuilder.UI/Views/DownloadWindow.axaml.cs
  WoWsShipBuilder.UI/Views/SplashScreen.axaml.cs
  WoWsShipBuilder.UI/Views/StartMenuWindow.axaml.cs
  WoWsShipBuilder.UI/WoWsShipBuilder.UI.csproj
  WoWsShipBuilder.ViewModels/Helper/BuildImportViewModelBase.cs
  WoWsShipBuilder.ViewModels/Other/SettingsWindowViewModelBase.cs
  WoWsShipBuilder.ViewModels/Other/ShipBuildViewModel.cs
  WoWsShipBuilder.ViewModels/Other/SplashScreenViewModel.cs
  WoWsShipBuilder.ViewModels/Other/StartMenuViewModelBase.cs
  WoWsShipBuilder.ViewModels/ShipVm/CaptainSkillSelectorViewModel.cs
  WoWsShipBuilder.ViewModels/ShipVm/ConsumableSlotViewModel.cs
  WoWsShipBuilder.ViewModels/ShipVm/ConsumableViewModel.cs
  WoWsShipBuilder.ViewModels/ShipVm/ShipViewModelBase.cs
  WoWsShipBuilder.ViewModels/ShipVm/SignalSelectorViewModel.cs
  WoWsShipBuilder.Web.Test/ServerAwsClientTest.cs
  WoWsShipBuilder.Web/Components/ShipStatsContainer.razor
  WoWsShipBuilder.Web/LinkShortening/FirebaseLinkShortener.cs
  WoWsShipBuilder.Web/Pages/ShipStats.razor
  WoWsShipBuilder.Web/Program.cs
  WoWsShipBuilder.Web/Services/ServerAppDataService.cs
  WoWsShipBuilder.Web/Services/ServerAwsClient.cs
  WoWsShipBuilder.Web/ViewModels/ShipViewModel.cs
  WoWsShipBuilder.Web/WoWsShipBuilder.Web.csproj
Labels: enhancement, Common
